# Builds
name: Action Integration Test
on:
  push:
jobs:
  action-integration-testing:
    name: Action Integration Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Copy in Dockerfile
        run: cp Docker/GHA-Dockerfile Dockerfile
      - name: Update action.yml to use dockerfile
        uses: rmeneely/update-yaml@v1
        with:
          infile: action.yml
          varlist: "runs.image=Dockerfile"
      - name: Test action
        id: test-action
        # test with the local checkout of the action
        uses: ./
        with:
          action: "validate"
          cookiecutter_desc_file_path: "tests/fixtures/valid/matching_pair/cookiecutter.desc"
          cookiecutter_json_file_path: "tests/fixtures/valid/matching_pair/cookiecutter.json"
